DEFINED_CLAUSES = [
    "Earnest Money Deposit (EMD)",
    "Mode of Earnest Money Submission",
    "Completion Period",
    "Mobilization Advance",
    "Security Deposit / Retention Money",
    "Defect Liability Period",
    "Performance Security",
    "Mode of Performance Security",
    "Price Variation Clause",
    "Incentive / Bonus Clause",
    "Site Investigation Clause",
    "Access to Site",
    "Working Hours & Night Work",
    "Utilities and Temporary Services",
    "Coordination with Other Contractors",
    "Material Testing and Quality Assurance",
    "Drawings and Technical Specifications",
    "As-Built Drawings and Documentation",
    "Handover Procedure",
    "Intellectual Property Rights (IPR)",
    "Permits and Approvals",
    "Third-Party Inspection Clause",
    "Health and Safety Plan Submission",
    "Progress Review Meetings",
    "Interim Certificate of Payment",
    "No Claim Certificate (NCC)",
    "Provisional Sum Items Clause",
    "Idle Machinery / Workforce Compensation",
    "Testing & Commissioning Requirements",
    "Dismantling and Debris Disposal Clause",
]
